default: &default
  adapter: postgresql
  encoding: unicode
  username: danylo
  password: qazwsx123
  pool: 5

development:
  <<: *default
  database: alpha_web_blog_development
  host: localhost

test:
  <<: *default
  database: alpha_web_blog_test
  host: localhost

production:
  <<: *default
  database: alpha_web_blog_production
  username: danylo
  secret: <%= ENV['SECRET_KEY_BASE'] %>
